### ISSUE TITLE
TypeInitializationException when starting C# agent

### ISSUE THREAD

**Issue by einsteinsci** [Microsoft/malmo#185]
Starting the C# agent results in a crash from a TypeInitializationException. Stacktrace:

```
System.TypeInitializationException: The type initializer for 'Microsoft.Research.Malmo.MalmoNETNativePINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'MalmoNETNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_MalmoNETNative(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.SWIGExceptionHelper..ctor()
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.new_AgentHost()
   at Program.Main()
```

Additionally, there is a warning when opening the CSPROJ in VS indicating that MalmoNETNative.dll isn't loaded:

```
The file '.\MalmoNETNative.dll' could not be added to the project.  Cannot add a link to the 
file C:\Users\sealedinterface\Documents\Malmo\CSharp_Examples\MalmoNETNative.dll.
This file is within the project directory tree.
```

Attempting to add the DLL to the project references results in the following error message:

```
A reference to 
'C:\Users\sealedinterface\Documents\Malmo\CSharp_Examples\MalmoNETNATIVE.dll' 
could not be added. Please make sure that the file is 
accessible, and that it is a valid assembly or COM component.
```

**Comment by einsteinsci** [comment]
I don't know how, but this issue suddenly fixed itself.

**Comment by einsteinsci** [comment]
It's back again, just as suddenly as it went away.

**Comment by einsteinsci** [comment]
I figured out the problem. I need to have `MalmoNETNative.dll` included in the project (not referenced), and set to always copy to the output directory.
