### ISSUE TITLE
behind corporate proxy, Connection timed out

### ISSUE THREAD

**Issue by jonygli** [Microsoft/malmo#221]
behind corporate proxy, on win7:

D:\developers\Malmo-0.15.0-Windows-64bit\Minecraft>launchClient.bat
Downloading https://services.gradle.org/distributions/gradle-2.7-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)

**Comment by DaveyBiggers** [comment]
Looks like there are some issues with using gradle behind a corporate proxy. A brief bit of googling turned up this: https://medium.com/@petehouston/execute-gradle-behind-a-corporate-proxy-network-509260961813#.bwb4r3e8g - I've no idea whether it works or not, but might be worth a shot.

**Comment by DaveyBiggers** [comment]
Hi @jonygli, did the link solve your problem? Have you managed to get up and running?

**Comment by DaveyBiggers** [comment]
Am closing this as I haven't heard anything for a while. Please reopen if it's still an issue.

**Comment by consentsam** [comment]
Yes it works @DaveyBiggers !
