### ISSUE TITLE
Occasionally no response when sending MissionInit

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#310]
Agent output:
```
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
```
(and nothing else, hanging)

Mod console:
```
...
[13:05:05] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:setState:101]: CLIENT enter state: WAITING_FOR_MOD_READY
[13:05:05] [Thread-13/INFO] [STDOUT]: [com.microsoft.Malmo.Utils.TCPInputPoller:run:191]: Listening for messages on port 10000
[13:05:05] [Client thread/INFO]: Logging in with username & password
[13:05:06] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:queueStateChange:143]: CLIENT request state: DORMANT
[13:05:06] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:setState:101]: CLIENT enter state: DORMANT
[13:06:03] [Thread-17/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:338]: Received from 127.0.0.1:
[13:06:03] [Thread-17/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:339]: <?xml version="1.0" encoding="UTF-8" standalone="no" ?><MissionInit xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ProjectMalmo.microsoft.com MissionInit.xsd"><Mission><About><Summary/></About><ServerSection><ServerInitialConditions><Time><StartTime>0</StartTime></Time></ServerInitialConditions><ServerHandlers><FlatWorldGenerator forceReset="true" generatorString="3;7,220*1,5*3,2;3;,biome_1" seed=""/><ServerQuitFromTimeUp description="" timeLimitMs="10000"/><ServerQuitWhenAnyAgentFinishes description=""/></ServerHandlers></ServerSection><AgentSection mode="Survival"><Name>Ant</Name><AgentStart><Placement pitch="30" x="-1.5" y="227" yaw="0" z="0.5"/></AgentStart><AgentHandlers><RewardForCollectingItem dimension="0"><Item reward="1" type="dirt"/></RewardForCollectingItem><RewardForDiscardingItem dimension="0"><Item reward="10" type="dirt"/></RewardForDiscardingItem><DiscreteMovementCommands/></AgentHandlers></AgentSection><AgentSection mode="Survival"><Name>Bee</Name><AgentStart><Placement pitch="30" x="1.5" y="227" yaw="180" z="6.5"/></AgentStart><AgentHandlers><RewardForCollectingItem dimension="0"><Item reward="10" type="dirt"/></RewardForCollectingItem><RewardForDiscardingItem dimension="0"><Item reward="100" type="dirt"/></RewardForDiscardingItem><DiscreteMovementCommands/></AgentHandlers></AgentSection></Mission><ExperimentUID/><ClientRole>0</ClientRole><ClientAgentConnection><ClientIPAddress>127.0.0.1</ClientIPAddress><ClientMissionControlPort>10000</ClientMissionControlPort><ClientCommandsPort>0</ClientCommandsPort><AgentIPAddress>127.0.0.1</AgentIPAddress><AgentMissionControlPort>10897</AgentMissionControlPort><AgentVideoPort>0</AgentVideoPort><AgentObservationsPort>10548</AgentObservationsPort><AgentRewardsPort>10813</AgentRewardsPort></ClientAgentConnection></MissionInit>
Exception in thread "Thread-17" [13:06:03] [Thread-17/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[13:06:03] [Thread-17/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.microsoft.Malmo.Client.ClientStateMachine$1.onCommand(ClientStateMachine.java:396)
[13:06:03] [Thread-17/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.microsoft.Malmo.Utils.TCPInputPoller.commandReceived(TCPInputPoller.java:232)
[13:06:03] [Thread-17/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.microsoft.Malmo.Utils.TCPInputPoller$TCPConnectionHandler.run(TCPInputPoller.java:326)
[13:06:03] [Thread-17/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Thread.run(Thread.java:745)
> Building 95% > :runClient
```

Platform: Windows.

Mod client must then be restarted.

Possibly related to #224

**Comment by timhutton** [comment]
No, sorry, my bad. I had local changes that introduced the NullPointerException in this situation.
