### ISSUE TITLE
Build error on Ubuntu 16.04

### ISSUE THREAD

**Issue by MadcowD** [Microsoft/malmo#397]
This seems fairly unique. Would love some help!
```
[22:23:12] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:168]: MALMO: Hooked into call to Minecraft.updateDisplay()
[22:23:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:52]: MALMO: Attempting to transform MinecraftServer
[22:23:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockServer:112]: MALMO: Found MinecraftServer, attempting to transform it
[22:23:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockServer:118]: MALMO: Found MinecraftServer.run() method, attempting to transform it
[22:23:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockServer:126]: MALMO: Transforming LDC
[22:23:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockServer:126]: MALMO: Transforming LDC
[22:23:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockServer:126]: MALMO: Transforming LDC
[22:23:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockServer:126]: MALMO: Transforming LDC
[22:23:13] [Client thread/INFO]: Setting user: Player168
[22:23:14] [Client thread/INFO]: LWJGL Version: 2.9.1
[22:23:14] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
Exception in thread "Client thread"     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
        at GradleStart.main(Unknown Source) [start/:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.crash.CrashReportCategory.firstTwoElementsOfStackTraceMatch(Unknown Source) ~[CrashReportCategory.class:?]
        at net.minecraft.crash.CrashReport.makeCategoryDepth(Unknown Source) ~[CrashReport.class:?]
        at net.minecraft.crash.CrashReport.makeCategory(Unknown Source) ~[CrashReport.class:?]
        at net.minecraft.client.Minecraft.run(Unknown Source) ~[Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Unknown Source) ~[Main.class:?]
        ... 12 more
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.reflect.Method.invoke(Method.java:498)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at GradleStart.main(Unknown Source)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(Unknown Source)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.Runtime.exit(Runtime.java:107)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.System.exit(System.java:971)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.launch.Launch.launch(Launch.java:138)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:23:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         ... 6 more
:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.284 secs
william@limbo-560:~/dev/minecraft-py/minecraft_py/Malmo/Minecraft$
```

**Comment by MadcowD** [comment]
[log.txt](https://github.com/Microsoft/malmo/files/573660/log.txt)

**Comment by katja-hofmann** [comment]
Hi William,

Sorry you're experiencing problems getting Malmo to run. Are you running
this inside a VM? I wonder if it's a display / driver issue.

If you're running Malmo headless, then issue #291 might help resolve this
problem. If not could you tell us a bit more about your setup?

Katja

**Comment by MadcowD** [comment]
That was the key, you can't run this headless without additional steps. Not sure if I missed this in the documentation.

Thanks
