### ISSUE TITLE
Version mismatch exceptions not propagated to Java etc

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#510]
Spotted as a result of #492 - if there is a mismatch in schema version numbers (eg if MALMO_XSD_PATH is pointing to an old copy of the schemas), the C++ code will throw a runtime exception in the AgentHost's constructor.

The python bindings handle this automatically - python will spit out a nice friendly error message.
The swigged languages don't handle this automatically. This is what the java user sees:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffeaa023c58, pid=11832, tid=4176
#
# JRE version: Java(TM) SE Runtime Environment (8.0_66-b18) (build 1.8.0_66-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b18 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x33c58]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# c:\Dev\Github\malmo\build\install\Java_Examples\hs_err_pid11832.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

CSharp users see this:
```
Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.new_AgentHost()
   at Program.Main()
```

C++ users get nothing but a crash - no message at all.

Best solution is probably simply to move the schema check from the AgentHost constructor to `startMission` - we expect startMission to throw, and most (all?) of our sample code wraps the call to startMission in a try/catch block. Our swig wrappers already handle exceptions in startMission so should require no other changes.

Except I have a nagging feeling that I put the check in the constructor for a reason...

**Comment by DaveyBiggers** [comment]
Fixed in b50e59d. Can't think of any particular downside to moving the check to startMission.
