### ISSUE TITLE
Error while installing Java

### ISSUE THREAD

**Issue by telezhnaya** [Microsoft/malmo#539]
Hello. When I try to install Malmo on new clear computer, I get this while I do malmo_install.ps1:
```
=============== 
Installing java 
=============== 

Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found." 
An error occurred, please check for error messages above. If the error persists, please raise an issue on https://github 
.com/Microsoft/malmo.
```

I tried to install Java by myself, everything goes fine until the final moments of launchClient.bat. It makes almost everything, but in the end of installing process it said:
```
[05:05:06] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.1.jar:?]
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.1.jar:?]
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252) ~[lwjgl-2.9.1.jar:?]
        at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.1.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.1.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.1.jar:?]
        at net.minecraft.client.Minecraft.createDisplay(Unknown Source) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.startGame(Unknown Source) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.run(Unknown Source) [Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Unknown Source) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
        at GradleStart.main(Unknown Source) [start/:?]
                                                                                                                       E
xception in thread "Client thread"                                                                                     [
05:05:07] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
        at GradleStart.main(Unknown Source) [start/:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.crash.CrashReportCategory.firstTwoElementsOfStackTraceMatch(Unknown Source) ~[CrashReportCatego
ry.class:?]
        at net.minecraft.crash.CrashReport.makeCategoryDepth(Unknown Source) ~[CrashReport.class:?]
        at net.minecraft.crash.CrashReport.makeCategory(Unknown Source) ~[CrashReport.class:?]
        at net.minecraft.client.Minecraft.run(Unknown Source) ~[Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Unknown Source) ~[Main.class:?]
        ... 12 more
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.Invoca
tionTargetException
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.N
ativeMethodAccessorImpl.invoke0(Native Method)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.N
ativeMe                                                                                                                t
hodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.D
elegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.ref
lect.Method.invoke(Method.java:498)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft
forge.gradle.GradleStartCommon.launch(Unknown Source)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at GradleStart.m
ain(Unknown Source)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: net.minecraft
forge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft
forge.fml.relauncher.FMLSecurityManager.checkPermission(Unknown Source)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.Sec
urityManager.checkExit(SecurityManager.java:761)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.Run
time.exit(Runtime.java:107)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.Sys
tem.exit(System.java:971)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft
.launchwrapper.Launch.launch(Launch.java:138)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft
.launchwrapper.Launch.main(Launch.java:28)
[05:05:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         ... 6 more
:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_131\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 43.085 secs
```

**Comment by telezhnaya** [comment]
2 weeks ago everything was fine. I installed Malmo smth around 10 times on different operating systems. And it was good.

When I tried to solve this problem, I have also tried to made gradlew clean, it does not help for me.

**Comment by DaveyBiggers** [comment]
These look like two separate issues...
The link to download Java had gone stale - I've changed it, so hopefully if you get the latest copy of the scripts folder from github it will work again - please let us know if it doesn't!
(Note that because you've manually installed Java, it won't attempt to re-install it - but it should work on a clean machine.)

The other issue looks like the error we see when there's no graphics card for Minecraft to use. Is this an Azure windows machine? If so, you'll need to install Mesa, the software renderer. The install_malmo script should do this automatically.

**Comment by telezhnaya** [comment]
I tried to install both in Azure (Windows 2016 Server) and locally (Windows 10), I had absolutely same problems. 
I will try now to make a new Azure VM, install everything with your changes and I will write here whether it works or not.
Thank you!

**Comment by telezhnaya** [comment]
Are you sure that it is enough to fix a problem? I removed Java, applied all your changes and invoked malmo_install.ps1. Java was installed succesfully but second problem remains the same.
By the way, I have found that line:
https://github.com/Microsoft/malmo/blob/master/scripts/malmo_install.ps1#L42
Sure that it's not a purpose but it must be also changed.

I will now make completely new VM for honest experiment, but I am sure that I will get same problem. Do you have another ideas how can I solve the second issue?
Thanks!

**Comment by DaveyBiggers** [comment]
Thank you for pointing out my oversight in malmo_install.ps1 - I've changed it.

I would expect the "Couldn't set pixel format" error on an Azure machine, which is why the install script tries to install the Mesa software renderer. (It does that by copying a file into the java directory, so if you've manually removed and reinstalled java, you've probably removed mesa along with it.)
I'm just running up an Azure VM myself to see if there's anything else going on.

I'm not sure why you are getting the problem locally on your Windows 10 machine, unless you have a very old graphics card? Try updating your drivers? Installing mesa should still fix things, either way.

To check whether you have mesa installed, look for a file called opengl32.dll in JAVA_HOME\bin.

**Comment by telezhnaya** [comment]
So, results:
I have made a new VM, copied a zip archive, extracted it and made all corrections related to Java update. After it I went through usual installation process and all was fine.
I have new Lenovo Yoga with Windows 10, sure that its graphics card is new enough. The problem, as I understood, is that script has the logic:
```python
if java not installed:
    install java
    install Mesa software renderer
else:
    pass
```
May be it will be better to do it like that:

```python
if java not installed:
    install java

try install Mesa software renderer
```

Because every person will have a problem if he will have Java without needed libraries.

**Comment by DaveyBiggers** [comment]
Glad the new VM is working okay.
On your Lenovo you shouldn't need Mesa - it's only needed in cases where hardware rendering is unavailable (eg running on Linux cluster machines with no display, or on Azure Windows machines where the remote desktop protocol forces software rendering).
(Though we do need to change the Mesa install logic anyway - #499).
If you are still having problems running on your local machine, perhaps you could open a new issue with the details?

**Comment by telezhnaya** [comment]
All is fine now. Thanks one more time!
