### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Nicolas99-9** [Microsoft/malmo#542]
Since today when I started Minecraft the window crashes  just before loading the menu. 

`11:00:24] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:-1]: ---- Minecraft Crash Report ----
// I feel sad now :(

Time: 30/05/17 11:00
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 4.8.0-52-generic
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 621162984 bytes (592 MB) / 783810560 bytes (747 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
OverclockingPlugin (unknown)
  com.microsoft.Malmo.OverclockingClassTransformer
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 12.0.6' Renderer: 'Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) '
[11:00:24] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[11:00:24] [Client thread/INFO] [FML]: MinecraftForge v11.14.3.1543 Initialized
[11:00:24] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[11:00:24] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[11:00:24] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[11:00:24] [Client thread/INFO] [FML]: Searching /home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/run/mods for mods
[11:00:25] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[11:00:25] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, malmomod] at CLIENT
[11:00:25] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, malmomod] at SERVER
[11:00:25] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Microsoft Malmo Mod
[11:00:25] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: MalmoMod in /home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/libs/MalmoMod-0.21.0.jar
[11:00:25] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: MalmoMod in /home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/libs/MalmoMod-0.21.0.jar
[11:00:25] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: MalmoMod in /home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/libs/MalmoMod-0.21.0.jar
[11:00:25] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[11:00:25] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[11:00:25] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[11:00:25] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[11:00:26] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[11:00:26] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Utils.SchemaHelper:testSchemaVersionNumbers:157]: Testing schemas against internal version number: 0.21
[11:00:26] [Client thread/INFO] [FML]: Applying holder lookups
[11:00:26] [Client thread/INFO] [FML]: Holder lookups applied
[11:00:26] [Client thread/INFO] [FML]: Injecting itemstacks
[11:00:26] [Client thread/INFO] [FML]: Itemstack injection complete
[11:00:26] [Client thread/INFO] [STDOUT]: [tv.twitch.StandardCoreAPI:<init>:16]: If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[11:00:26] [Client thread/ERROR]: Couldn't initialize twitch stream
[11:00:26] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:00:26] [Thread-8/INFO]: Initializing LWJGL OpenAL
[11:00:26] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:00:26] [Thread-8/INFO]: OpenAL initialized.
[11:00:26] [Client thread/INFO] [FML]: Max texture size: 8192
[11:00:26] [Client thread/INFO]: Created: 16x16 textures-atlas
[11:00:26] [Sound Library Loader/INFO]: Sound engine started
[11:00:27] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[11:00:27] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.3.1543.jar) 
	UCHI	Forge{11.14.3.1543} [Minecraft Forge] (forgeSrc-1.8-11.14.3.1543.jar) 
	UCHE	malmomod{0.21.0} [Microsoft Malmo Mod] (MalmoMod-0.21.0.jar) 
[11:00:27] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[11:00:27] [Client thread/ERROR] [FML]: Caught exception from malmomod
java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft;
	at com.microsoft.Malmo.Client.MalmoModClient.init(MalmoModClient.java:97) ~[MalmoMod-0.21.0.jar:?]
	at com.microsoft.Malmo.MalmoMod.init(MalmoMod.java:145) ~[MalmoMod-0.21.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(Unknown Source) ~[forgeSrc-1.8-11.14.3.1543.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(Unknown Source) ~[forgeSrc-1.8-11.14.3.1543.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(Unknown Source) ~[forgeSrc-1.8-11.14.3.1543.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAcces.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(Unknown Source) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Unknown Source) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(Unknown Source) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Unknown Source) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Unknown Source) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Unknown Source) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
[11:00:27] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:-1]: ---- Minecraft Crash Report ----
// Oops.

Time: 30/05/17 11:00
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft;
	at net.minecraftforge.fml.common.LoadController.transition(Unknown Source)
	at net.minecraftforge.fml.common.Loader.initializeMods(Unknown Source)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(Unknown Source)
	at net.minecraft.client.Minecraft.startGame(Unknown Source)
	at net.minecraft.client.Minecraft.run(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft;
	at com.microsoft.Malmo.Client.MalmoModClient.init(MalmoModClient.java:97)
	at com.microsoft.Malmo.MalmoMod.init(MalmoMod.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatidAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(Unknown Source)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(Unknown Source)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 4.8.0-52-generic
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 716145576 bytes (682 MB) / 902299648 bytes (860 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1543 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.3.1543.jar) 
	UCHI	Forge{11.14.3.1543} [Minecraft Forge] (forgeSrc-1.8-11.14.3.1543.jar) 
	UCHE	malmomod{0.21.0} [Microsoft Malmo Mod] (MalmoMod-0.21.0.jar) 
	Loaded coremods (and transformers): 
OverclockingPlugin (unknown)
  com.microsoft.Malmo.OverclockingClassTransformer
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 12.0.6' Renderer: 'Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) '
[11:00:27] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:-1]: #@!@# Game crashed! Crash report saved to: #@!@# /home/nicolas/miniconda2/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/run/./crash-reports/crash-2017-05-30_11.00.27-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.676 secs
`

**Comment by DaveyBiggers** [comment]
Interesting. I've seen something like this before, but only on the SockLogs / MultiHardening branch, where I've been experimenting with a more direct command-line for running Minecraft. Can I confirm which version of Malmo you are using?
(If you're on the branch, you can temporarily fix this by deleting runMC.sh / runMC.bat)

**Comment by DaveyBiggers** [comment]
Am closing this due to lack of response, but please re-open if it's still an issue.
