### ISSUE TITLE
Fail to launch client on AWS

### ISSUE THREAD

**Issue by MicroSTM** [Microsoft/malmo#566]
I am trying to launch client on AWS, but build failed with the error: 

> What went wrong:
Execution failed for task ':runClient'.
Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

I tried the solution provided by @katja-hofmann on #291 but still failed.

I also tried to launch clients on my laptop and run other code on AWS. But I could not connect to my laptop on AWS and therefore could not add the ports (e.g., 127.0.0.1:10000) on my laptop as clients. I tried ssh port forwarding, but it did not work either.

Is there a way to solve either of the problems?

**Comment by katja-hofmann** [comment]
Hi @MicroSTM,

we're running Malmo on Azure with `xvfb-run` - I would expect this to work on AWS as well. We've found it convenient to use docker - you can see https://github.com/Microsoft/malmo-challenge/tree/master/docker for examples.

If this doesn't work for you, could you provide more information on what goes wrong, e.g., how you set up the machine, and the complete error trace?

To run a distributed setup between laptop and cloud, you'd have to configure the cloud service's firewall to allow access to and and from your local machine (and ideally from no-where else). Then you'll need to use the cloud machine's public IP, instead of a local 127.0... In Azure, you can configure the firewall through Azure Portal. I have no experience specific to AWS - if someone else does, please feel free to chip in with pointers.

**Comment by MicroSTM** [comment]
Hi @katja-hofmann , thanks for the suggestions. I am using Ubuntu 16.04 on my AWS instance. I tried to use xvfb-run w/o docker and got the following error:

> [18:43:53] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Could not init GLX
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:846) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:615) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.init(Minecraft.java:469) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:387) [Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
        at GradleStart.main(GradleStart.java:26) [start/:?]
[18:43:54] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

> Time: 6/24/17 6:43 PM
Description: Initializing game

> org.lwjgl.LWJGLException: Could not init GLX
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828)
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
        at org.lwjgl.opengl.Display.create(Display.java:846)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:635)
        at net.minecraft.client.Minecraft.init(Minecraft.java:469)
        at net.minecraft.client.Minecraft.run(Minecraft.java:387)
        at net.minecraft.client.main.Main.main(Main.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
        at GradleStart.main(GradleStart.java:26)


> A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

> -- Head --
Thread: Client thread
Stacktrace:
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828)
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
        at org.lwjgl.opengl.Display.create(Display.java:846)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:635)
        at net.minecraft.client.Minecraft.init(Minecraft.java:469)

> -- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.run(Minecraft.java:387)
        at net.minecraft.client.main.Main.main(Main.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
        at GradleStart.main(GradleStart.java:26)

> -- System Details --
Details:
        Minecraft Version: 1.11.2
        Operating System: Linux (amd64) version 4.4.0-81-generic
        Java Version: 1.8.0_131, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1341018960 bytes (1278 MB) / 1507852288 bytes (1438 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 1 total; -Xmx2G
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: 
        Loaded coremods (and transformers): 
OverclockingPlugin (MalmoMod-0.30.0.jar)
  com.microsoft.Malmo.OverclockingClassTransformer
        Launched Version: 1.11.2
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps: 
        Using VBOs: No
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs: 
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>
[18:43:54] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: #@!@# Game crashed! Crash report saved to: #@!@# /home/ubuntu/MalmoPlatform/Minecraft/run/./crash-reports/crash-2017-06-24_18.43.54-client.txt
:runClient FAILED

> FAILURE: Build failed with an exception.

>* What went wrong:
>Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

> * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

> BUILD FAILED

>Total time: 10.877 secs

**Comment by MicroSTM** [comment]
I finally figured out the issue. Turns out that I just need to reinstall GPU driver and CUDA with no opengl options, and then ``xvfb-run`` will work. Details: https://davidsanwald.github.io/2016/11/13/building-tensorflow-with-gpu-support.html

**Comment by katja-hofmann** [comment]
Brilliant! Thank you for figuring this out and for posting your solution!
