### ISSUE TITLE
Tutorial 3: Can't find module 'past'

### ISSUE THREAD

**Issue by debadeepta** [Microsoft/malmo#600]
Using the latest 0.31 64-bit build on Windows 10. Tutorial 3 throws an error (see below) because it can't find past. I am using Anaconda python distribution. Both conda and conda-forge channels  don't have this module.

(malmo-py3.6) C:\Users\dedey\Documents\Malmo-0.31.0-Windows-64bit_Python3.6\Malmo-0.31.0-Windows-64bit_Python3.6\Python_Examples>python tutorial_3.py
Traceback (most recent call last):
  File "tutorial_3.py", line 25, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'

**Comment by DaveyBiggers** [comment]
From the release notes:

> All our sample/test python code has been "futurised" to work with both Python 2 and Python 3. This shouldn't be a breaking change, but there may now be an extra dependency to install - try pip install future if the samples don't seem to be working.

past is part of the future module (sounds very zen) - you should get it by installing future.
Let us know if this solves your problem, and I'll update the documentation accordingly.

**Comment by marcusnguyen** [comment]
I'm getting this error even after I have installed future.

$ pip install future
Requirement already satisfied: future in c:\program files (x86)\python36-32\lib\site-packages (0.16.0)

$ py -3 mob_fun.py
Traceback (most recent call last):
  File "mob_fun.py", line 25, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'

**Comment by AndKram** [comment]
pip3 install future?

**Comment by nmandhana** [comment]
It do not solve the problem after installing future
