### ISSUE TITLE
Mac xerces-x import error

### ISSUE THREAD

**Issue by carl24k** [Microsoft/malmo#637]
Hi, I'm trying to run an example for the first time after installing the required packages with homebrew on Mac OS X 10.12.6.  I check that i've got xerces-c and I'm using the system python.  When I try to run an example I see the error below.  Any idea what the problem could be?

MacBook-Air-3:Python_Examples $ brew ls --versions xerces-c
xerces-c 3.2.0
MacBook-Air-3:Python_Examples $ /usr/bin/python run_mission.py
Traceback (most recent call last):
File "run_mission.py", line 20, in
import MalmoPython
ImportError: dlopen(/Users/carl/Malmo/Python_Examples/MalmoPython.so, 2): Library not loaded: /usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib
Referenced from: /Users/carl/Malmo/Python_Examples/MalmoPython.so
Reason: image not found

**Comment by carl24k** [comment]
I'm pretty sure this is something related to my brew setup, and I am searching related articles,  trying to understand the output of brew doctor, etc.  No luck yet.

**Comment by carl24k** [comment]
Its the same thing if I explicitly /usr/bin/python as recommended in the instructions:

MacBook-Air-3:Python_Examples $ /usr/bin/python run_mission.py
Traceback (most recent call last):
  File "run_mission.py", line 20, in <module>
    import MalmoPython
ImportError: dlopen(/Users/carl/Malmo/Python_Examples/MalmoPython.so, 2): Library not loaded: /usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib
  Referenced from: /Users/carl/Malmo/Python_Examples/MalmoPython.so
  Reason: image not found

**Comment by carl24k** [comment]
Okay, I have made some progress figuring this out:  I have xerces-c 3.2, not 3.1, and  MalmoPyathon.so is specifically looking for 3.1.

MacBook-Air-3:Python_Examples $ ls /usr/local/opt/xerces-c/lib/
cmake			libxerces-c-3.2.dylib	libxerces-c.so		pkgconfig

So far I have been unable to install xerces-c 3.1 with brew (trying to use these instructions : https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula)

Also, trying to trick it by making a symbolic link from libxerces-c-3.1.dylib to the libxerces-c-3.2.dylib that I have did not work.  It gives an error Symbol not found: __ZN11xercesc_3_111InputSource11setEncodingEPKt
  Referenced from: ./MalmoPython.so
  Expected in: /usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib

**Comment by shamtasm-1** [comment]
I'm also getting the same issue. I could not figure out how to install xerces 3.1 using brew.

Here's what I tried, using a random fork of legacy-homebrew:

```
jamie$ brew install https://raw.githubusercontent.com/foca/homebrew/master/Library/Formula/xerces-c.rb
######################################################################## 100.0%
Error: Calling Formula.md5 is disabled!
Use Formula.sha256 instead.
/Users/jamie/Library/Caches/Homebrew/Formula/xerces-c.rb:6:in `<class:XercesC>'
```

It looks like the current version of brew doesn't like the old formula. It probably makes more sense to upgrade malmo to xerces 3.2. How different can a new XML parser really be?

**Comment by ZhiruiFeng** [comment]
I met the same problem. Have anyone of you solved it?

**Comment by andrew-blake** [comment]
The URL and hash needed fixing.

I've tweaked it at: https://gist.github.com/andrew-blake/5f43c47b832ca99bac06b3283f168cd5

`brew install https://gist.github.com/andrew-blake/5f43c47b832ca99bac06b3283f168cd5/raw/a59338351a698575243472254f9ec531baed0825/xerces-c.rb`

**Comment by carl24k** [comment]
It works!  Thank you @andrew-blake !  After that I was able to run `/usr/bin/python run_mission.py` without errors, and the Minecraft client responded, etc.  (Some weird issues observed there as far as mouse control of my desktop, but thats another thing...)

Note to others, if you already installed xerces-c 3.2 you will need to `brew unlink xerces-c` before running the command shown above.

**Comment by DaveyBiggers** [comment]
@carl24k glad you are up and running. Out of interest, did you try building Malmo on OSX, or were you running a pre-built version?
I'd have thought that Malmo would happily build and run against xerces 3.2, and I can't see any reason why it would be looking for 3.1 specifically. But it does link dynamically against xerces, so if we built it against 3.1 then this would explain the problem... It's the same problem we had with versions of boost, and the solution would be to link statically against xerces (eg see #476).

If this is indeed the problem, then a better workaround for Mac users might be to build Malmo themselves - it's a very simple procedure on Mac. I don't know what changed between 3.1 and 3.2 of xerces, but it seems a shame to downgrade!

**Comment by carl24k** [comment]
This was running with the pre-built version.  I also tried building but got stuck there and haven't gotten back that again yet.  I don't think there were any errors during the build, but my build failed the tests at test 16, PythonTests_test_wrapping with a seg fault.  If I recall correctly I also got some kind of seg fault when I tried to launch the client (which is why I was running the test...)  I  looked some of the things mentioned on https://github.com/Microsoft/malmo/pull/449 but nothing really helped.  If you think the Mac build should work then I'll give it another go some time soon.  Maybe I had something wrong in my setup or build that I missed.
