### ISSUE TITLE
Malmo docker crashes

### ISSUE THREAD

**Issue by okkhoy** [Microsoft/malmo#655]
I built a docker image as per the docker file [here](https://github.com/Microsoft/malmo-challenge/blob/master/docker/malmo/Dockerfile). 
I changed Malmo version to 0.31 and updated the links to fetch the correct version.

The build is successful; however, when I run the docker, Malmo crashes with the following stack trace.

The trace looks similar to the one in #644. Not sure if it is the same issue. (Please feel free to close the issue if it is a dup.)

```
[22:49:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/24/18 10:49 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.minecraft.client.Minecraft.setWindowIcon(Minecraft.java:670)
	at net.minecraft.client.Minecraft.init(Minecraft.java:467)
	at net.minecraft.client.Minecraft.run(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.setWindowIcon(Minecraft.java:670)
	at net.minecraft.client.Minecraft.init(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.4.0-62-generic
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1371781936 bytes (1308 MB) / 1561329664 bytes (1489 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
OverclockingPlugin (MalmoMod-0.31.0.jar)
  com.microsoft.Malmo.OverclockingClassTransformer
	Launched Version: 1.11.2
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
[22:49:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: #@!@# Game crashed! Crash report saved to: #@!@# /root/Malmo/Minecraft/run/./crash-reports/crash-2018-01-24_22.49.07-client.txt
:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.846 secs
```

**Comment by DaveyBiggers** [comment]
@okkhoy did you ever get this working?
We've been doing some work that involved running Malmo headless within a docker container, and found that there were problems using xvfb, so we switched to using xpra - eg:

```
sudo apt-get install xpra
xpra start :100
export DISPLAY=:100
./launchClient.sh
etc.
```
I've found this to be reliable - let me know if it helps.

**Comment by okkhoy** [comment]
- I could not get the docker to start, every time I tried, I got the same stack dump as above.

- I changed `xvfb` to `xpra` in the docker file and edited the run.sh to include the following lines:
```
xpra start :100
export DISPLAY=:100
```
I leave it to the docker to start Minecraft run as earlier.

There is no crash, but it seems nothing is running. I just get the following output:

```
$ docker run malmo-docker
2018-03-14 15:36:13,798 rencode import error: No module named rencode

Warning: running as root
```

I don't think malmo is running!

Did I miss something?

**Comment by okkhoy** [comment]
@DaveyBiggers I noticed using `xpra` solves the problem on the bare-metal server. I am able to launch headless. However, docker is still a problem (as described above, I don't think Minecraft started on the docker).

**Comment by jayhardee9** [comment]
@okkhoy if you still need this to work with Docker, you just need to add `python-rencode` to the list of packages to install in the Dockerfile you linked, along with `xpra`. The "import error" you received was xpra's Python not finding the rencode module.

Also, change `run.sh` to:
```bash
#!/bin/sh

xpra start :100
export DISPLAY=:100
eval $*
```
Malmo didn't run because the last line of your Dockerfile:
```
ENTRYPOINT ["/root/run.sh", "/root/Malmo/Minecraft/launchClient.sh"]
```
is passing "/root/Malmo/Minecraft/launchClient.sh" as a parameter to `run.sh`. So whatever you change `run.sh` to will need to run its command line arg.

**Comment by okkhoy** [comment]
@jayhardee9 thanks for the pointer. I will try this next week and update/close this issue.
