### ISSUE TITLE
Minecraft launch crash on Ubuntu server - LWJGLException

### ISSUE THREAD

**Issue by EC2EZ4RD** [Microsoft/malmo#755]
I tried to launch Minecraft by `launchClient.sh` on headless Ubuntu server.
I don't have the root privilege, and it's hard for me to install xpra etc. But I can display gedit or xclock on my laptop.
The crash report shows that an error `org.lwjgl.LWJGLException: Could not choose visual`, and the crash report is below.

Can anyone help me out?

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/17/18 3:25 PM
Description: Initializing game

org.lwjgl.LWJGLException: Could not choose visual
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828)
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
        at org.lwjgl.opengl.Display.create(Display.java:846)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:635)
        at net.minecraft.client.Minecraft.init(Minecraft.java:469)
        at net.minecraft.client.Minecraft.run(Minecraft.java:387)
        at net.minecraft.client.main.Main.main(Main.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
        at GradleStart.main(GradleStart.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828)
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
        at org.lwjgl.opengl.Display.create(Display.java:846)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:635)
        at net.minecraft.client.Minecraft.init(Minecraft.java:469)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.run(Minecraft.java:387)
        at net.minecraft.client.main.Main.main(Main.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
        at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
        Minecraft Version: 1.11.2
        Operating System: Linux (amd64) version 4.4.0-45-generic
        Java Version: 1.8.0_152-release, JetBrains s.r.o
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), JetBrains s.r.o
        Memory: 1250822536 bytes (1192 MB) / 1427111936 bytes (1361 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 1 total; -Xmx2G
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML:
        Loaded coremods (and transformers):
OverclockingPlugin (MalmoMod-0.36.0.jar)
  com.microsoft.Malmo.OverclockingClassTransformer
        Launched Version: 1.11.2
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps:
        Using VBOs: No
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>

**Comment by EC2EZ4RD** [comment]
I did as you said, but the issue is still existing.
