### ISSUE TITLE
Problem in installing minecraft(launchClient.bat)

### ISSUE THREAD

**Issue by ID56** [Microsoft/malmo#781]
Installed MalmoEnv following the instructions. When calling 'launchClient.bat -port 9000 -env', the installation goes through smoothly, and the build is successful.
![minecraft](https://user-images.githubusercontent.com/38450043/49168380-8e534800-f361-11e8-858f-21682a6b2c4c.png)

Minecraft successfully launches- and then crashes four or five seconds later. Here's the error report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 11/28/18 11:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Microsoft Malmo Mod (malmomod)
Caused by: java.lang.RuntimeException: This mod has been incorrectly built; check schema version numbers.
	at com.microsoft.Malmo.MalmoMod.preInit(MalmoMod.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:643)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:268)
	at net.minecraft.client.Minecraft.init(Minecraft.java:478)
	at net.minecraft.client.Minecraft.run(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 117338208 bytes (111 MB) / 474480640 bytes (452 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.11.2-13.20.0.2228.jar) 
	UCH	forge{13.20.0.2228} [Minecraft Forge] (forgeSrc-1.11.2-13.20.0.2228.jar) 
	UCE	malmomod{unspecified} [Microsoft Malmo Mod] (MalmoMod.jar) 
	Loaded coremods (and transformers): 
OverclockingPlugin (MalmoMod.jar)
  com.microsoft.Malmo.OverclockingClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4771' Renderer: 'Intel(R) HD Graphics 620'

**Comment by ID56** [comment]
Also says the following at the end:

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'D:\Java\JDK\bin\java.exe'' finished with non-zero exit value -1

**Comment by AndKram** [comment]
What install instructions are you following? I note the "-env" arg to launchClient.bat that is used with the new Python implementation of the OpenAI "gym" environment API. Thanks.

**Comment by ZacharyATanenbaum** [comment]
Hello everyone,

I am having the same problem on both Windows 10 and Arch. The exact same error at the exact same location. I tried @AndKram 's suggestion changing the .xsd files but that does not seem to fix the error. Has anyone figured out the problem?

**Comment by ZacharyATanenbaum** [comment]
Hey AndKram thank you for the reply! I tried installing  MalmoEnv cleanly. I didn't realize we had to clone a specific branch from those instructions. I will try those instructions again if you pushed changes to the main branch as well as checkout another branch if that doesn't work.

**Comment by AndKram** [comment]
I tried it on a clean Linux docker and found that the instructions for creating the version.properties file were wrong. I've fixed it now: (echo -n "malmomod.version=" && cat ../VERSION) > ./src/main/resources/version.properties) so hopefully it will work for you. MalmoEnv is new so unfortunately you are on the "bleeding edge" but that for testing it! Please check that you end up with malmomod=0.37.0 in the version.properties file in src/main/resources. Cheers, Andre.

**Comment by Russell-Tran** [comment]
> I tried it on a clean Linux docker and found that the instructions for creating the version.properties file were wrong. I've fixed it now: (echo -n "malmomod.version=" && cat ../VERSION) > ./src/main/resources/version.properties) so hopefully it will work for you. MalmoEnv is new so unfortunately you are on the "bleeding edge" but thank you for testing it! Please check that you end up with malmomod=0.37.0 in the version.properties file in src/main/resources. Cheers, Andre.

Hi! I'm still having trouble with this

**Comment by wowbob396** [comment]
Hi Russell! I ran into the same issue that you are facing, and I believe what you want to put into the version file is: malmomod.version=VERSION_NUMBER where VERSION_NUMBER is the value inside of the VERSION file. I just pulled the repo, so I put: 
malmomod.version=0.37.0

inside of malmo/Minecraft/src/resources/version.properties
