### ISSUE TITLE
SEHException exception

### ISSUE THREAD

**Issue by ileonidmas** [Microsoft/malmo#782]
Hi,
I am trying play around with malmo. I have created MVC project where I run minecraft agents in the background, save the videos and then display it to the user. Everything works perfectly when I run the project locally from Visual Studio as an administrator. As soon as I publish it on a local IIS server which I create on the same machine, I get this error. 

Crash at following point:System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.AgentHost_startMission__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4, Int32 jarg5, String jarg6)
   at Microsoft.Research.Malmo.AgentHost.startMission(MissionSpec mission, ClientPool client_pool, MissionRecordSpec mission_record, Int32 role, String unique_experiment_id)
   at RunMission.Evolution.MalmoClient.TryStartMission() in C:\Users\JohnSmith\Documents\Github\MinecraftCIEC\malmoTestAgentInterface\Evolution\MalmoClient.cs:line 184

Is there a way how I can solve it? Thank you =)

**Comment by AndKram** [comment]
AgentHost does access local files, for example the xsd schema files which is probably failing in IIS?

**Comment by ileonidmas** [comment]
Yes, it does access local files. We also thought that it might be an issue, so we have added Schemas to a bin folder with all the permisions to the IIS folder where we have our application and changed the eniromental variables to point to the Schemas folder. The error still persists. Moreover, I tried to give all permissions to Malmo folder with all the source code etc, but it didnt work
