### ISSUE TITLE
ModuleNotFoundError: No module named 'MalmoPython'; pip install python 3.7 macOS Mojave

### ISSUE THREAD

**Issue by tomsilver** [microsoft/malmo#829]
Thanks for your work on malmo! I am trying to do a clean install with pip using python 3.7 on macOS Mojave. I am following [these instructions](https://github.com/Microsoft/malmo/blob/master/scripts/python-wheel/README.md).

When attempting to run the example script, I encounter the following error:

`ModuleNotFoundError: No module named 'MalmoPython'`

Here are steps to reproduce what I am seeing after doing the prerequisites.

```
Toms-MacBook-Pro-3:phd tom$ mkdir minecraft_clean
Toms-MacBook-Pro-3:phd tom$ cd minecraft_clean/
Toms-MacBook-Pro-3:minecraft_clean tom$ pyenv local 3.7.0
Toms-MacBook-Pro-3:minecraft_clean tom$ virtualenv venv --no-site-packages
Using base prefix '/Users/tom/.pyenv/versions/3.7.0'
New python executable in /Users/tom/phd/minecraft_clean/venv/bin/python3.7
Also creating executable in /Users/tom/phd/minecraft_clean/venv/bin/python
Installing setuptools, pip, wheel...
done.
Toms-MacBook-Pro-3:minecraft_clean tom$ source venv/bin/activate
(venv) Toms-MacBook-Pro-3:minecraft_clean tom$ pip install malmo
Collecting malmo
  Using cached https://files.pythonhosted.org/packages/a5/12/71cfbf665a6b4c98e329691d738884721412072d08006e71367e3963dc4b/malmo-0.36.0.0-cp37-cp37m-macosx_10_13_x86_64.whl
Installing collected packages: malmo
Successfully installed malmo-0.36.0.0
(venv) Toms-MacBook-Pro-3:minecraft_clean tom$ python -c 'import malmo.minecraftbootstrap; malmo.minecraftbootstrap.download()'
Cloning into 'MalmoPlatform'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 15280 (delta 18), reused 34 (delta 15), pack-reused 15236
Receiving objects: 100% (15280/15280), 28.14 MiB | 9.85 MiB/s, done.
Resolving deltas: 100% (9888/9888), done.
Please make sure you set the MALMO_XSD_PATH environment variable to "/Users/tom/phd/minecraft_clean/MalmoPlatform/Schemas"!
(venv) Toms-MacBook-Pro-3:minecraft_clean tom$ export MALMO_XSD_PATH=/Users/tom/phd/minecraft_clean/MalmoPlatform/Schemas
(venv) Toms-MacBook-Pro-3:minecraft_clean tom$ python -c 'import malmo.minecraftbootstrap; malmo.minecraftbootstrap.launch_minecraft()'
Nothing is listening on port 10000 - will attempt to launch Minecraft from a new terminal.
Giving Minecraft some time to launch... 
(venv) Toms-MacBook-Pro-3:minecraft_clean tom$ python -c 'from malmo.run_mission import run; run()'
Traceback (most recent call last):
  File "/Users/tom/phd/minecraft_clean/venv/lib/python3.7/site-packages/malmo/run_mission.py", line 32, in <module>
    import MalmoPython
ModuleNotFoundError: No module named 'MalmoPython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tom/phd/minecraft_clean/venv/lib/python3.7/site-packages/malmo/run_mission.py", line 35, in <module>
    import malmo.MalmoPython as MalmoPython
ImportError: dlopen(/Users/tom/phd/minecraft_clean/venv/lib/python3.7/site-packages/malmo/MalmoPython.so, 2): Library not loaded: /usr/local/opt/boost-python3/lib/libboost_python37-mt.dylib
  Referenced from: /Users/tom/phd/minecraft_clean/venv/lib/python3.7/site-packages/malmo/MalmoPython.so
  Reason: image not found
```

I understand from the documentation that this error can occur when attempting to build from source, but I am not -- I am installing with pip.

Thanks for your help!

**Comment by AndKram** [comment]
I recently built a new binary release which may work for you: https://github.com/microsoft/malmo/releases/download/0.37.0/Malmo-0.37.0-Mac-64bit_withBoost_Python3.7.zip. The wheel seems to no longer find dependencies that used to be installed with boost.

**Comment by tomsilver** [comment]
Thanks! I am making do with malmoenv for now. It would be good to put a note in the documentation in case others try to pip install malmo in the meantime.

**Comment by AndKram** [comment]
There's a new native wheel for MacOS for Python 3.7. It may work for you - if not some investigation of missing dependencies (boost python most likely), for example running ldd on MalmoPython.so would be helpful.

**Comment by DaveyBiggers** [comment]
I'm closing this due to inactivity - if there is still an issue that needs resolving, please reopen and provide more details, thanks!
