### ISSUE TITLE
cant run run_mission.py on pre-built for windows

### ISSUE THREAD

**Issue by ZackYovel** [microsoft/malmo#854]
Followed all the instructions, but when running python run_mission.py from the Python_Examples folder I get this error:

> >python run_mission.py
> Traceback (most recent call last):
>   File "run_mission.py", line 32, in <module>
>     import MalmoPython
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "run_mission.py", line 35, in <module>
>     import malmo.MalmoPython as MalmoPython
> ImportError: DLL load failed: The specified module could not be found.

**Comment by Gicminos** [comment]
I have the same issue

**Comment by nmurali2002** [comment]
Did you get this to work? Have same issue using Python 3.7, automated install.

**Comment by dwaffe** [comment]
I have the same problem

**Comment by dwaffe** [comment]
thanks to #876 I just find zlib.dll on my computer (OBS studio have such file) and copy to Python_Example - it works. I hope next version will have zlib.dll included
