### ISSUE TITLE
java.lang.reflect.InvocationTargetException thrown when launching client

### ISSUE THREAD

**Issue by ChristopherMillon** [microsoft/malmo#871]
Operating System: `Windows 10`
Malmo version: `Malmo-0.37.0-Windows-64bit_withBoost_Python3.7`

```
PS C:\Users\chris\Malmo-0.37.0-Windows-64bit_withBoost_Python3.7\Minecraft> .\launchClient.bat
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-3966cea
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches
:remapMcSources SKIPPED
:recompileMc SKIPPED
:extractNatives SKIPPED
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 978/1196   81%
:makeStart
:setupDecompWorkspace

BUILD SUCCESSFUL

Total time: 24.03 secs
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-3966cea
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient
:copyModToServer
:deleteSchemas
:copySchemas
:jaxb
:sourceMainJava
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:processResources
:classes
:jar
:sourceTestJava
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:getVersionJson
:extractUserdev UP-TO-DATE
:genSrgs SKIPPED
:reobfJar
:assemble
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 16.428 secs
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-3966cea
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient
:copyModToServer
:deleteSchemas
:copySchemas
:jaxb UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:processResources UP-TO-DATE
:classes
:jar
:getVersionJson
:extractNatives SKIPPED
:extractUserdev UP-TO-DATE
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 988/1196   82%
:makeStart
:runClient
2020-03-29 19:41:49,196 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2020-03-29 19:41:49,198 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[19:41:49] [main/INFO] [GradleStart]: Extra: []
[19:41:49] [main/INFO] [GradleStart]: Found and added coremod: com.microsoft.Malmo.OverclockingPlugin
[19:41:49] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/chris/.gradle/caches/minecraft/assets, --assetIndex, 1.11, --accessToken{REDACTED}, --version, 1.11.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[19:41:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:41:49] [main/INFO] [FML]: Forge Mod Loader version 13.20.0.2228 for Minecraft 1.11.2 loading
[19:41:49] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_242, running on Windows 10:amd64:10.0, installed at C:\Program Files\AdoptOpenJDK\jdk-8.0.242.08-hotspot\jre
[19:41:49] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[19:41:49] [main/INFO] [FML]: Found a command line coremod : com.microsoft.Malmo.OverclockingPlugin
[19:41:49] [main/WARN] [FML]: The coremod com.microsoft.Malmo.OverclockingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:41:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[19:41:49] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[19:41:49] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[19:41:49] [main/INFO] [GradleStart]: Injecting location in coremod com.microsoft.Malmo.OverclockingPlugin
[19:41:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:41:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:41:49] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[19:41:50] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[19:41:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:41:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:41:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:41:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[19:41:50] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:41:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:41:50] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:41:50] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:58]: MALMO: Attempting to transform MinecraftServer
[19:41:50] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:187]: MALMO: Found Minecraft, attempting to transform it
[19:41:50] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:193]: MALMO: Found Minecraft.runGameLoop() method, attempting to transform it
[19:41:50] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:208]: MALMO: Hooked into call to Minecraft.updateDisplay()
[19:41:50] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.EntityPlayerSP
[19:41:50] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.AbstractClientPlayer
2020-03-29 19:41:51,034 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2020-03-29 19:41:51,062 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2020-03-29 19:41:51,064 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[19:41:51] [main/ERROR] [LaunchWrapper]: Unable to launch
Exception in thread "main" java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
       at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
     at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ExceptionInInitializerError
   at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3033) ~[Minecraft.class:?]
      at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
   ... 12 more
Caused by: java.lang.NullPointerException
  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847) ~[?:1.8.0_242]
     at java.lang.Runtime.loadLibrary0(Runtime.java:871) ~[?:1.8.0_242]
     at java.lang.System.loadLibrary(System.java:1124) ~[?:1.8.0_242]
       at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_242]
   at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
      at org.lwjgl.Sys.loadLibrary(Sys.java:87) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
  at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3033) ~[Minecraft.class:?]
      at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
   ... 12 more
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.reflect.InvocationTargetException
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.reflect.Method.invoke(Method.java:498)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at GradleStart.main(GradleStart.java:26)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at java.lang.Runtime.exit(Runtime.java:108)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at java.lang.System.exit(System.java:973)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:41:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        ... 6 more
:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.86 secs
```

**Comment by ChristopherMillon** [comment]
Same as https://github.com/microsoft/malmo/issues/870
